style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/axllent/mailpit
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    title_maps:
      feature: Feature
      fix: Fix
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
    sort_by: Custom
    title_order:
      - Feature
      - Chore
      - UI
      - API
      - Libs
      - Docker
      - Security
      - Fix
      - Bugfix
      - Docs
      - Swagger
      - Build
      - Testing
      - Test
      - Tests
      - Pull Requests
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
