on:
  release:
    types: [created]

name: Build & release
jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, freebsd, netbsd, openbsd]
        goarch: ["386", amd64, arm, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm
            goos: darwin

    steps:
    - uses: actions/checkout@v3

    # build the binaries
    - uses: wangyoucao577/go-release-action@v1.38
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        binary_name: "sndmail"
        pre_command: export CGO_ENABLED=0
        asset_name: sndmail-${{ matrix.goos }}-${{ matrix.goarch }}
        extra_files: LICENSE README.md sndmail.conf.example
        md5sum: false
        overwrite: true
        ldflags: -s -w -X "github.com/axllent/sndmail/cmd.Version=${{ github.ref_name }}"
